#Time in UTC (18:00 is 11:00PST)
time:
  hour: 18
  minute: 00

#Threshold (Celcius)
threshold: [20, 25, 30]

#
#    Everything below here you have to get yourself
#

#Discord Bot API key here
key: ''

#Channel ID to send the bot message to
channel: 0

#Open-Meteo API Request URL here 
meteo: ''

#Latitude/Longitude (this will update with meteo)
coord:
  latitude: 0
  longitude: 0
