#Time in UTC (16:00 is 09:00PST)
time:
  hour: 16
  minute: 00

#Location to pull weather data from
location: 'Richmond, Canada'

#Threshold (Celcius)
threshold: 20

#
#    Everything below here you have to get yourself
#

#Discord Bot API key and Weatherstack API key here
keys:
  bot: ''
  weatherstack: ''

#Channel ID to send the bot message to
channel: 0