#Time in UTC (Example: 18:00UTC = 11:00PDT)
time:
  hour: 18
  minute: 00

#Threshold (Celcius)
threshold: [20, 25, 30]

#Latitude/Longitude (YOU CAN IGNORE THIS)
coord:
  latitude: 0
  longitude: 0


#
#    Everything below here you have to get on your own
#

#Discord bot access key here
key: 

#Channel ID to send the bot message to
channel: 0

#Open-Meteo API Request URL here. Look at the GitHub guide to get the correct parameters for the URL
meteo: 

